# Generated by Django 4.0.4 on 2022-06-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='customer',
        ),
    ]
