# Generated by Django 4.0.4 on 2022-07-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_remove_item_cart_remove_item_product_cart_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(blank=True, default='1', null=True, related_name='items', to='cart.item'),
        ),
    ]
