# Generated by Django 4.0.4 on 2022-07-07 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_alter_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
