# Generated by Django 4.0.4 on 2022-08-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_cart_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='item',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
