# Generated by Django 4.0.4 on 2022-08-03 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_remove_cart_total_amount_item_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='total_amount',
        ),
    ]
