# Generated by Django 4.0.4 on 2022-08-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_cart_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_amount',
        ),
    ]
