# Generated by Django 4.0.4 on 2022-08-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_remove_cart_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
