# Generated by Django 4.0.4 on 2022-07-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_timestamp_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
