# Generated by Django 4.0.4 on 2022-07-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_choice',
            field=models.CharField(blank=True, choices=[('card', 'card'), ('case_on_delivery', 'case_on_delivery')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
