# Generated by Django 4.0.4 on 2022-07-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_payment_date_payment_transection_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_choice',
        ),
    ]
