# Generated by Django 4.0.4 on 2022-07-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_remove_payment_payment_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_choice',
            field=models.CharField(blank=True, choices=[('card', 'card'), ('case_on_delivery', 'case_on_delivery')], max_length=20, null=True),
        ),
    ]
