# Generated by Django 4.0.4 on 2022-06-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_sub_category'),
        ('order', '0002_remove_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(default='1', to='product.product'),
        ),
    ]
