# Generated by Django 4.0.4 on 2022-06-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_category'),
        ('order', '0014_remove_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ManyToManyField(default='1', related_name='order_items', to='product.product'),
        ),
    ]
