# Generated by Django 4.0.4 on 2022-07-05 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_cart_product_remove_item_item_item_cart_and_more'),
        ('order', '0017_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='cart.cart'),
        ),
    ]
