# Generated by Django 4.0.4 on 2022-07-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
