# Generated by Django 4.0.4 on 2022-07-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
