# Generated by Django 4.0.4 on 2022-07-15 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_rename_total_order_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_cost',
            new_name='total_amount',
        ),
    ]
