# Generated by Django 4.0.4 on 2022-07-15 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_orderitem_points_gained'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='points_gained',
        ),
    ]
