# Generated by Django 4.0.4 on 2022-07-15 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_remove_orderitem_points_gained'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
