# Generated by Django 4.0.4 on 2022-07-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_remove_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
